### PR TITLE
Remove outdated badges

### PR DESCRIPTION
**Pull request by mlhetland**
Remove SVG badges that no longer exist. They could be replaced, but in their current form, they simply don't work.

### CODE REVIEW

**Comment by kescobo** [comment]
Sorry for letting this languish - any chance you'd be willing to update / rebase?

**Comment by mlhetland** [comment]
Did that work?-)

**Comment by mirkobunse** [comment]
The diff looks perfect, but why does the PR show 15 commits?

**Comment by mlhetland** [comment]
Uh. I probably messed up rebase/merge, somehow? Dunno. Feel free to scrap the PR and just do the edit directly!-D It's entirely trivial, after all.

**Comment by kescobo** [comment]
I think this is a merge with all of the intervening commits. @mlhetland I'd suggest the following - on your open branch:

```
$ cp README.md ~/Desktop
$ git remote add upstream https://github.com/JuliaData/YAML.jl.git # assuming you haven't done this already
$ git reset --hard upstream master # this is a destructive operation
$ mv ~/Desktop/README.md ./
$ git commit -am "Remove outdated badges"
$ git push -f # force overwrite
```

This is kinda a manual rebase, since you've only changed one file. Alternatively, I'm happy to do it manually if you don't want to bother :-)

**Review by christopher-dG — APPROVED** [review]
We should probably merge this now.

**Pull request merged**
