### PR TITLE
Prevent EOL newlines conversion by Git

### PR DESCRIPTION
**Pull request by Paalon**
~Would~ solve #216.

- Fix EOL for normal test YAML files LF.
- With postfix `.crlf.yaml` file use CRLF.
- Change windows_newlines content from `"hello:\r\n\r"` to `"hello:\r\n"`.

### CODE REVIEW

**Comment by GunnarFarneback** [comment]
I don't think we should do this and if #219 works as expected there should be no need for it.

**Comment by kescobo** [comment]
So should this and #216 be closed?

**Comment by GunnarFarneback** [comment]
I think this went in with #218 and I still think it would be better to let Windows work natively in the tests.

**Comment by kescobo** [comment]
Oh, so we want to revert that bit of #218 you mean?

**Comment by GunnarFarneback** [comment]
Yes, that's my take on it.

**Comment by kescobo** [comment]
Should we edit this issue, or open a new one for that?

**Comment by kescobo** [comment]
Oh yeah, it will require a new PR, I'm just wondering if we're ok using this issue to track that.

**Comment by kescobo** [comment]
And now I see that this IS a PR.... my bad...

**Pull request closed without merging**
