### PR TITLE
Quote and escape strings with repr

### PR DESCRIPTION
**Pull request by mirkobunse**
This PR directly follows from the discussion in #90

### CODE REVIEW

**Comment by christopher-dG** [comment]
I think this does fix the issue but it also means that we lose multiline strings, which can be very useful.

On YAML 0.4.2:
```jl
julia> println(YAML.write(Dict("foo" => """{\n  "pretty": "json"\n}""")))
foo: |
    {
      "pretty": "json"
    }
```

Personally I would suggest the following:

```yml
a: "plain string"
b: "with a trailing newline, the string is no less readable\n"
c: |
  with
  multiple
  lines
d: |
  with "quotes" inside it
e: |
  with tricky \ backslashes
```

**Comment by mirkobunse** [comment]
Thanks for your comment!

I agree, actual multi-line strings would be a nice feature. However, I can also imagine that some users actually prefer the single-line fully-escaped solution (or do not care), e.g. when their gut feeling about property `c` was that a single line is more concise. In the long run, we should provide an argument `newlines` (or similar) to make the user choose how to handle them. We should then set the default to the behavior you proposed.

My intention behind this PR is to make `YAML.write` work in the first place. We can handle style in another PR.

**Comment by christopher-dG** [comment]
I'm happy to make another PR to handle style. Reason being I'm using YAML for saving HTTP response bodies which are often pretty-printed JSON.

**Comment by kescobo** [comment]
Is there any reason anyone can see to not merge this - looks good to me (but I jumped the gun last time...)

**Review by kescobo — APPROVED** [review]

**Comment by christopher-dG** [comment]
I'm pretty sure this should be bulletproof, if not aesthetically pleasing 😄

**Comment by kescobo** [comment]
Good enough for me!

**Pull request merged**
