### PR TITLE
Provocation: Use multiple dispatch instead of typeof checks. 

### PR DESCRIPTION
**Pull request by polytomous**
Howdy! I love this code, and figured I'd take some time to get familiar with it and see if I could do any fun refactorings.

From my python experience, I'm loathe to include `typeof` checks in my code, and I have a strong belief that multiple dispatch, for the most part, gives us a way to avoid most of that style of programming. 

I feel that the strategy I've employed also makes many of the weird typeof-in-a-set call patterns in the code more readable by changing them to multiple dispatch against a union type. 

The main reason to make this PR isn't so much to add the code to YAML.jl (I'm loathe to have to maintain or be responsible for code that Real Serious People need on a daily basis.) but rather to get some feedback. Is this kind of use of multiple dispatch any good? I feel it basically gives us pattern matching semantics, and that seems *extremely good* to me. 

What are y'alls feelings about this?

### CODE REVIEW

**Comment by polytomous** [comment]
Thank you so much for the feedback! 

Before I begin: I agree with concerns about performance, but I'll supply this meme as to why I wasn't immediately concerned with it when I wrote the PR. 😜 Since I'm coming from Python primarily, I have radically different expectations about how fast things are supposed to go. 
image

On type inference with the closures: I'm pretty sure that most of these closures are going to be type stable. Most of them only return `::Void`, and the others could be brought into line on that front. Not 100% sure though, and since I'm a greenhorn with Julia I still probably am missing stuff here. 

If this was python, it'd be a guarantee that the closures would get reinterpreted every run, and that would definitely hamper performance. (The extent to which it would may not be too bad, but it'd certainly have some non-zero cost.) 

In julia, I'm unsure. If they're jitted once, and then julia doesn't re-JIT them again and again, then the performance hit from compilation is just the one time you JIT, or whenever you precompile. That's not really that bad, all things considered. But it's possible that's not the case. I can convince myself that this is how things go, but you're right that we need either benchmarks or an enlightened compiler expert to weigh in. 

I don't think the multiple dispatch part of the process itself is too concerning: any of these functions have incredibly small method lists, so there's a relatively limited amount of type checking that goes into the process. At most 2-5 checks of type info down the method list, and most of the call patterns probably hit the cache  in the case that the methods aren't recompiled all the time. But of course, that's more work than doing just an if statement, so there will be *some* performance cost. 

I think the sneaky thing here is that some of the smaller functions that have been defined as closures could be pulled out into the outer scope with the only required change being modifying the names so they don't collide. In composer.jl for example, most of the `compose!` methods only consume values in their parameters, so they don't have to reside inside the methods. Unfortunately we can't use that strategy for any of the `parse!` methods as easily. 

So, yes: I need to do some more work measuring the performance of this change. I'd like to take some time to really sit down and think through what I need to do to profile this correctly. I have a vague intuition of the tools that I need to use for this in the julia ecosystem (it looks like Tim Holy has some gorgeous stuff written for profiling visualizations 😻  ) but will need more time. Additionally, I'd like to get a better sense for how other yaml libraries across other languages do their benchmarking. In a perfect world I'd just be able to coopt some other set of benchmark data and set up the appropriate test harnesses for this library and make nice actionable data out of it all. (And everyone would be much happier as a result ;) ) 

I don't want to take that work on *right this second*, so I'm very comfortable with this pull request disappearing for a while until I've actually taken reasonable measurements. I will say, in my defense, that i didn't see the kind of performance degradation that i saw when i tried to use functions as dictionaries with a healthy amount of `eval` shenanigans and dispatching with the `Val{X}` trick. (It's actually kind of silly how well that all works)  

----

 But, let's assume for a moment that the performance does degrade more than anticipated. What's the acceptable tradeoff between performance and expressiveness? Personally, I find this: 

```
if !in(typeof(peek(stream.input)), [KeyToken, ValueToken, BlockEndToken])
```

very hard to read. I have to really think through what is going on, and it just doesn't feel natural. The ergonomics for this change, however, feel nicer:

```
function parse!(token::Union{KeyToken, ValueToken, BlockEndToken}) 
```

I mean, I can practically read the type declaration to get a sense of what's happening here. "Parse! a token:: that is a `KeyToken`, `ValueToken`, or `BlockEndToken`" 

That feels *so* right to me. Maybe performance should be damned. 😜  

We can table this for now, and I'll ping back someday when I've actually done the right measurements. Thanks again for your time. You're the best 🥇 👍

**Comment by bjarthur** [comment]
i've riffed on the idea here of using function barriers to improve type stability, and run performance tests.  along with a couple other tweaks i get 2x faster.  see https://github.com/BioJulia/YAML.jl/pull/64

**Comment by kescobo** [comment]
@polytomous is this idea still live, or does #64 supersede it?

**Comment by polytomous** [comment]
@kescobo no, this idea is not live. I'm nuking my github account and don't desire for my contributions to be merged by a TERF contributor. closing.

**Comment by kescobo** [comment]
For anyone stumbling on this later, this almost certainly refers to [this discussion](https://discourse.julialang.org/t/ethics-in-julia/43232/70?u=kevbonham) on discourse. Let me know if I'm the asshole here (but probably in a different venue).

**Pull request closed without merging**
