### PR TITLE
Accept colon at YAML directive

### PR DESCRIPTION
**Pull request by nlw0**
YAML files sometimes have this "%YAML:1.0" directive, and apparently the colon is not only allowed, but necessary. Currently the parser breaks at any files with this directive and this patch intends to fix that.

Also adding a `Project.toml` file that has apparently become necessary in Julia 1.4.

### CODE REVIEW

**Comment by nlw0** [comment]
Waiting for #75 to rebase and remove the Project.toml

**Comment by nlw0** [comment]
I finally looked again at this...

**Comment by nlw0** [comment]
@kescobo This is the PR I was talking about at Slack

**Comment by kescobo** [comment]
:+1: - I'll give it a couple of days. If I haven't replied by Friday, feel free to bug me again here or on slack

**Pull request merged**
