### PR TITLE
Add type assertions of the functions in `src/composer.jl`.

### PR DESCRIPTION
**Pull request by Paalon**
### Original title: Refactor `src/composer.jl`

* Add type assertions for all function arguments.
* Remove redundant new lines.
* Remove `return` at the end of the function.
* Add new lines to decrease the number of characters per line.

### CODE REVIEW

**Comment by Paalon** [comment]
I formatted to my favorite style but it is not absolute.

**Comment by Paalon** [comment]
I split this PR to type assertions and style formatting.

**Comment by Paalon** [comment]
Now, this PR only includes type assertions.

**Review by kescobo — COMMENTED** [review]
I'm certainly not against this in principle, but is there a compelling need for it? It does not (typically) improve speed, and in this case I think the argument names are pretty clear, so annotating them with types doesn't add much clarity.

I don't feel stongly, just something to consider.

**Comment by GunnarFarneback** [comment]
It definitely won't make a difference to speed, but it adds a small amount of clarity and gives a faster error if you make a mistake when making code changes, so I think it's an improvement.

**Comment by Paalon** [comment]
I think this can be safely merged. @kescobo Can you merge this?

**Pull request merged**
