### PR TITLE
Remove `equivalent` and chomping

### PR DESCRIPTION
**Pull request by Paalon**
Remove `equivalent` and change to `isequal` and remove chomping.

I think `equivalent` for `AbstractString` and input chomping do something wrong. With chomping, Some tests are failed.

### CODE REVIEW

**Comment by Paalon** [comment]
What the failing tests means is that we can't treat trailing newlines appropriately in Windows.

**Comment by Paalon** [comment]
There is issue #102.

**Comment by GunnarFarneback** [comment]
I think the Windows test failures are another manifestation of the failure to load empty documents. You can simulate this on Linux with
```
julia> first(YAML.load_all("---\r\nx:\r\n...\r\n"))
ERROR: AssertionError: forward!(composer.input) isa DocumentStartEvent
```

**Comment by Paalon** [comment]
I merged #217 into this. Now all tests are passed and solves #102.

**Comment by Paalon** [comment]
Now does not depend on any PRs.

**Review by GunnarFarneback — APPROVED** [review]

**Review by kescobo — APPROVED** [review]

**Pull request merged**
